# Generated by Django 2.0.7 on 2018-07-14 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0002_blockpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockPage',
            new_name='BlogPage',
        ),
    ]
